apiVersion: apps/v1
kind: Deployment
metadata:
  name: myserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myserver
  strategy: {}
  template:
    metadata:
      labels:
        app: myserver
    spec:
      containers:
      - image: nginxdemos/hello:0.2
        name: myserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path:  /
            port:  80
        readinessProbe:
          httpGet:
            path: /
            port: 80
