apiVersion: v1
kind: Service
metadata:
  name: myserver
  labels:
    app: myserver
spec:
  selector:
    app: myserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
